### ISSUE TITLE
Nota

### ISSUE THREAD

**Issue by fsantanna-uerj** [Vini300/EDL#2]
Favor dividir 22.5 pontos entre vocês.                                            
A nota máxima é 8.

**Comment by Vini300** [comment]
Professor, como todos nós trabalhamos igualmente no trabalho, decidimos dividir a nota igualmente também. Portanto, decidimos que cada um de nós deve receber 7.5 como a nota do trabalho.

**Comment by fsantanna-uerj** [comment]
ok
